name: jumppoint_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # third party plugins - make sure all plugins must be a web support and with null safety
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_screenutil: ^5.5.3+2
  connectivity_plus: ^2.3.5
  flutter_statusbarcolor_ns: ^0.4.0
  intl: ^0.17.0
  http: ^0.13.3
  shared_preferences: ^2.0.6
  json_annotation: ^4.5.0
  path_provider:
  open_file:
  fluttertoast: ^8.0.9
  build_runner: ^2.1.11
  flutter_svg:
  badges: ^2.0.3
  dropdown_plus: ^0.0.9
  flutter_native_splash:
  mobile_scanner: ^2.0.0
  qr_code_scanner:
  excel: 2.0.0-null-safety-3
  permission_handler:
  animations:
  flutter_staggered_animations:
  platform_device_id:
  universal_html:
  universal_io:
  #FirebaseMessaging
  firebase_core:
  firebase_messaging:
  flutter_local_notifications:
  #Webview
  webview_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.2.0
  flutter_launcher_icons: ^0.9.3

flutter_native_splash:
  image: assets/images/jump_point_icon.png
  image_dark: assets/images/jump_point_icon.png
  color: "#EB5236"
  color_dark: "#EB5236"
  android: true
  ios: true
  web: true
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center
  android_screen_orientation: sensorPortrait
  fullscreen: true

  #background_image: "assets/background.png"
  #branding: assets/dart.png
  #branding_mode: bottom

  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png
  #branding_dark: assets/dart_dark.png

  android_12:
    image: assets/images/round_logo.png
    image_dark: assets/images/round_logo.png
    color: "#EB5236"
    color_dark: "#EB5236"
    android: true
    ios: true
    web: true
    android_gravity: center
    ios_content_mode: center
    web_image_mode: center
    android_screen_orientation: sensorPortrait
    fullscreen: true
  # The image parameter sets the splash screen icon image.  If this parameter is not specified,
  # the app's launcher icon will be used instead.
  # Please note that the splash screen will be clipped to a circle on the center of the screen.
  # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
  # 640 pixels in diameter.
  # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
  # 768 pixels in diameter.
  #image: assets/android12splash.png

  # App icon background color.
  #icon_background_color: "#FFFFFF"
  #icon_background_color_dark: "#FFFFFF"

  #image_andriod: assets/splash-andriod.png
  #image_dark_android: assets/splash-invert-android.png
  #image_ios: assets/splash-ios.png
  #image_dark_ios: assets/splash-invert-ios.png
  #image_web: assets/splash-web.png
  #image_dark_web: assets/splash-invert-web.png
  #background_image_android: "assets/background-android.png"
  #background_image_dark_android: "assets/dark-background-android.png"
  #background_image_ios: "assets/background-ios.png"
  #background_image_dark_ios: "assets/dark-background-ios.png"
  #background_image_web: "assets/background-web.png"
  #background_image_dark_web: "assets/dark-background-web.png"
  #branding_andriod: assets/brand-android.png
  #branding_dark_android: assets/dart_dark-android.png
  #branding_ios: assets/brand-ios.png
  #branding_dark_ios: assets/dart_dark-ios.png

  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito_bold.ttf
        - asset: assets/fonts/nunito_light.ttf
        - asset: assets/fonts/nunito_medium.ttf
        - asset: assets/fonts/nunito_regular.ttf
        - asset: assets/fonts/nunito_semibold.ttf
